# Generated by Django 5.0.6 on 2024-07-07 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(
                    upload_to='posts/images/', blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(
                    related_name='post_likes', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(
                    default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
