# Generated by Django 5.0.6 on 2024-07-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_body_post_content_rename_date_post_posted_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
