# Generated by Django 5.0.6 on 2024-07-07 08:54

# posts/migrations/0004_post_slug.py

from django.db import migrations, models
import django.utils.text
import django.utils.crypto


def populate_slug(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    for post in Post.objects.all():
        if not post.slug:
            post.slug = django.utils.text.slugify(
                post.content[:50]) + '-' + django.utils.crypto.get_random_string(6)
            post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20240707_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.RunPython(populate_slug),
    ]
