# Generated by Django 5.0.6 on 2024-07-15 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0007_comment_is_flagged'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flag',
            name='content_type',
            field=models.ForeignKey(
                default=7, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flag',
            name='object_id',
            field=models.PositiveIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flag',
            unique_together={('content_type', 'object_id', 'user')},
        ),
    ]
