# Generated by Django 5.0.6 on 2024-07-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_flag_unique_together_flag_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='post',
        ),
    ]
